# Generated by Django 4.0.1 on 2022-01-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_makale'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='resim',
            field=models.ImageField(default='adsdasdas', upload_to='blog/'),
            preserve_default=False,
        ),
    ]
